import Head from 'next/head';
import { Box } from '@mui/system';
import Header from './Header';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useEffect, useContext } from 'react';
import FoodContext, { FoodContextType } from '../context/FoodContext';
import styles from '../styles/Layout.module.scss';

type LayoutType = {
  children: React.ReactNode;
};
const Layout = ({ children }: LayoutType): JSX.Element => {
  const { toastMsg } = useContext(FoodContext) as FoodContextType;
  useEffect(() => {
    if (toastMsg.msg) {
      if (toastMsg.type === 'error') {
        toast.error(toastMsg.msg, { autoClose: 500 });
      }
      if (toastMsg.type === 'success') {
        toast.success(toastMsg.msg, { autoClose: 500 });
      }
    }
  }, [toastMsg]);
  return (
    <>
      <Head>
        <title>Frontend Next.js Task</title>
        <meta name="description" content="Generated by baaalint@codingsans" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Box component="main" className={styles.main}>
        {children}
      </Box>
      <ToastContainer />
    </>
  );
};

export default Layout;
